pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                script {
                    git branch: 'main',
                        credentialsId: 'Credential ID',
                        url: 'https://github.com/deepak-323/Pipeline.git'
                }
            }
        }
	stage('Install dependencies') {
            steps {
                // Install Python dependencies
                sh 'pip install -r requirements.txt'
            }
        }
	stage('Test') {
            steps {
                script { // Your build commands go here 
	          sh "chmod +x -R ${env.WORKSPACE}" 
		  sh '/usr/bin/python3 /var/lib/jenkins/workspace/pipeline-1/TF_Inference_cifar.py'
		  sh "echo ${currentBuild.number}"
	       }
            }
        }
	stage('Archive Artifacts') {
            steps {
                // Archive the artifacts (output files) generated by your script
                archiveArtifacts artifacts: '*'
		sh "tar czvf ${currentBuild.number}.tar.gz *"
            }
        }
	stage('Upload to S3') {
            steps {
                script {
                    
		    sh "aws s3 sync /var/lib/jenkins/jobs/pipeline-1/builds/${currentBuild.number}.tar.gz s3://mcw-pipeline/Artifacts"

                }
            }
        }
}
      
   
 }

